const { User } = require('../models');

const userData = [
  {
    first_name: 'Katie',
    last_name: 'Menendez',
    username: 'identifykentish',
    email: 'kmenendez2@example.com',
    password: 'password',
    city: 'Lynnwood',
    state: 'WA',
    // zip: 98501,
    organization: '',
    // street: '1820 11th Ave SE',
  },
  {
    first_name: 'Dominic',
    last_name: 'Freeman',
    username: 'retaingoring',
    email: 'lionspark@example.com',
    password: 'password',
    city: 'Lynnwood',
    state: 'WA',
    // zip: 98501,
    organization: 'Lions Park',
    // street: '800 Wilson St. SE',
  },
  {
    first_name: 'Tyson',
    last_name: 'Green',
    username: 'nebulousdominate',
    email: 'redcarhero@example.com',
    password: 'password',
    city: 'Shoreline',
    state: 'WA',
    // zip: 98502,
    organization: '',
    // street: '818 Decatur St SW',
  },
  {
    first_name: 'Zoe',
    last_name: 'Franklin',
    username: 'totalcounselor',
    email: 'zoeisawesome@example.com',
    password: 'password',
    city: 'Seattle',
    state: 'WA',
    // zip: 98502,
    organization: '',
    // street: '822 Milroy St SW',
  },
  {
    first_name: 'Hope',
    last_name: 'Gao',
    username: 'allyaddicted',
    email: 'hopegao@example.com',
    password: 'password',
    city: 'San Antonio',
    state: 'TX',
    // zip: 98501,
    organization: 'Thurston County Food Bank',
    // street: '220 Thurston Ave NE',
  },
  {
    first_name: 'Jason',
    last_name: 'Wolfe',
    username: 'vaguepaver',
    email: 'hungrylikethewolfe@example.com',
    password: 'password',
    city: 'Everett',
    state: 'WA',
    // zip: 98502,
    organization: '',
    // street: '2926 Langridge Loop NW',
  },
  {
    first_name: 'Jazmine',
    last_name: 'Wilson-Brown',
    username: 'enragedinfection',
    email: 'jazzercise@example.com',
    password: 'password',
    user_city: 'Bellevue',
    user_state: 'WA',
    // zip: 98502,
    organization: '',
    // street: '1611 10th Ave SW, Olympia',
  },
  {
    first_name: 'Sakura',
    last_name: 'Fujino',
    username: 'infinitedifferent',
    email: 'sakurafujino@example.com',
    password: 'password',
    city: 'Olympia',
    state: 'WA',
    // zip: 98501,
    organization: '',
    // street: '4934 Donovan Dr SE',
  },
];

const seedUser = () => User.bulkCreate(userData);

module.exports = seedUser;
